### ISSUE TITLE
can't load json files 

### ISSUE THREAD

**Issue by r4ph74** [victorlucachi/void9#2]
hi .. I'm just new in QMK and Via .. 

I tried to load your json file, but it comes up with error .. 

![image](https://user-images.githubusercontent.com/87015888/134674731-f88692ac-7d01-46c2-9857-273d7a23d394.png)

May I know what is wrong ? do I have to plug the keyboard first before I can see the layout ? 

Thanks in Advance 

Regards, 

Rafael

**Comment by victorlucachi** [comment]
Hey Rafael!

Any additional info on the issue? The JSON seems to be loading just fine for me.

![image](https://user-images.githubusercontent.com/2669084/134797033-9299763a-3ce5-47e0-ac80-6890c678537f.png)
