### ISSUE TITLE
Miss location pin out for colom 0 and colom 1 

### ISSUE THREAD

**Issue by r4ph74** [victorlucachi/void9#5]
hi victor , 

I just finally finish my macropad.. Thans for your tutorial . 

but there is something miss in pinout  between col 0 and col 1.  

I guess it should be 

Col 0  D1 
Col1  D0

btw do you have the tutorial  for replacing one button top left with the Rotary encoder ? 

I have been thinking to create another one with Rotary encoder with  the same matrix .

regards, 

Rafael

![image](https://user-images.githubusercontent.com/87015888/169299906-c5e1e9a0-c153-4c69-bdcc-1ca4f81ae40a.png)

**Comment by victorlucachi** [comment]
Awesome, but I'm not sure I follow, what's missing?

the guide that is linked in the repo with the stl files has two of the columns swapped (my mistake), in case that you followed it, but all of the switches should be working. this pinout is the correct one.

    ROW0    ROW1    ROW2
    F4      F5      F6
    
    
    COL0    COL1    COL2
    D1      D0      D4

if you dont want to desolder the wiring you can edit your local qmk copy and swap `D1` with `D0` and viceversa [here](https://github.com/victorlucachi/qmk_firmware/blob/19b94e044d59df27a358f8ca4e5fce5bd4e106ec/keyboards/handwired/void9/info.json#L16), and recompile the firmware

two encoders are enabled by default after my latest changes to the repo; they're relatively easy to wire in.

ec11 style encoders have 5 pins, 2 on one side, 3 on the opposing side.

the side with 2 pins gets wired into the matrix like a regular switch
on the side with 3 pins, the middle one goes to a ground pin on the microcontroller, while the outer two pins get wired to the microcontroller pins assigned in the firmware; by default these pins are the following:

     #define ENCODERS_PAD_A { B1, B2 }
     #define ENCODERS_PAD_B { F7, B3 }

to be clear, if you want to wire only one encoder in, the outer two pins would get wired to B1 and F7, or B2 and B3. it's up to you which pair you choose.

**Comment by r4ph74** [comment]
the tutorial I follow is on your website .. https://victorlucachi.ro/journal/void9-wiring-guide/

![image](https://user-images.githubusercontent.com/87015888/169375723-8b51e7e7-2994-4fbf-a601-e30f5e2bf0f9.png)

it's all working great now. .. still learning how to configure it with Via :)


-------------

I'm not sure I can follow, but I will make sure it when making another one with the encoder. I will ask you again . 


Thanks alot Victor. 


-------

**Comment by r4ph74** [comment]
btw How to change the name of the USB instead of Void9 ?
