### ISSUE TITLE
Void16 Compiling errors/issues [using a RP2040 as controller]

### ISSUE THREAD

**Issue by darknessblade** [victorlucachi/void9#6]
Hello, I have some issues trying to compile the void16 using a RP2040 as controller

`
$ qmk compile -kb handwired/void16rp2040 -km default
Ψ Compiling keymap with make --jobs=1 handwired/void16rp2040:default

QMK Firmware 0.18.13
☒ handwired/void16rp2040: NO_ACTION_MACRO in config.h is no longer a valid option and should be removed
☒ handwired/void16rp2040: NO_ACTION_FUNCTION in config.h is no longer a valid option and should be removed
Making handwired/void16rp2040 with keymap default

☒ handwired/void16rp2040: NO_ACTION_MACRO in config.h is no longer a valid option and should be removed
☒ handwired/void16rp2040: NO_ACTION_FUNCTION in config.h is no longer a valid option and should be removed
Generating: .build/obj_handwired_void16rp2040/src/default_keyboard.c                                [WARNINGS]
 |
 | ☒ handwired/void16rp2040: NO_ACTION_MACRO in config.h is no longer a valid option and should be removed
 | ☒ handwired/void16rp2040: NO_ACTION_FUNCTION in config.h is no longer a valid option and should be removed
 |
arm-none-eabi-gcc.exe (GCC) 10.1.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Generating: .build/obj_handwired_void16rp2040/src/info_config.h                                     [WARNINGS]
 |
 | ☒ handwired/void16rp2040: NO_ACTION_MACRO in config.h is no longer a valid option and should be removed
 | ☒ handwired/void16rp2040: NO_ACTION_FUNCTION in config.h is no longer a valid option and should be removed
 |
Generating: .build/obj_handwired_void16rp2040/src/default_keyboard.h                                [WARNINGS]
 |
 | ☒ handwired/void16rp2040: NO_ACTION_MACRO in config.h is no longer a valid option and should be removed
 | ☒ handwired/void16rp2040: NO_ACTION_FUNCTION in config.h is no longer a valid option and should be removed
 |
Generating: .build/obj_handwired_void16rp2040/src/layouts.h                                         [WARNINGS]
 |
 | ☒ handwired/void16rp2040: NO_ACTION_MACRO in config.h is no longer a valid option and should be removed
 | ☒ handwired/void16rp2040: NO_ACTION_FUNCTION in config.h is no longer a valid option and should be removed
 |
Compiling: .build/obj_handwired_void16rp2040/src/default_keyboard.c                                In file included from <command-line>:
./keyboards/handwired/void16rp2040/config.h:13:1: error: "/*" within comment [-Werror=comment]
   13 | /* Debounce reduces chatter (unintended double-presses) - set 0 if debouncing is not needed */
      |
./keyboards/handwired/void16rp2040/config.h:16:1: error: "/*" within comment [-Werror=comment]
   16 | /* disable these deprecated features by default */
      |
./keyboards/handwired/void16rp2040/config.h:17:1: error: unterminated comment
   17 | /*#ifndef LINK_TIME_OPTIMIZATION_ENABLE
      | ^
cc1.exe: all warnings being treated as errors
 [ERRORS]
 |
 |
 |
make[1]: *** [builddefs/common_rules.mk:359: .build/obj_handwired_void16rp2040_default/.build/obj_handwired_void16rp2040/src/default_keyboard.o] Error 1
Make finished with errors
make: *** [Makefile:414: handwired/void16rp2040:default] Error 1

`
Configuration:
[void16rp2040.zip](https://github.com/victorlucachi/void9/files/9722852/void16rp2040.zip)

**Comment by darknessblade** [comment]
Compiling the normal setup gives no issues
`$ qmk compile -kb handwired/void16 -km default
Ψ Compiling keymap with make --jobs=1 handwired/void16:default


QMK Firmware 0.18.13
☒ handwired/void16: NO_ACTION_MACRO in config.h is no longer a valid option and should be removed
☒ handwired/void16: NO_ACTION_FUNCTION in config.h is no longer a valid option and should be removed
Making handwired/void16 with keymap default

☒ handwired/void16: NO_ACTION_MACRO in config.h is no longer a valid option and should be removed
☒ handwired/void16: NO_ACTION_FUNCTION in config.h is no longer a valid option and should be removed
avr-gcc.exe (GCC) 8.5.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Generating: .build/obj_handwired_void16/src/info_config.h                                           [WARNINGS]
 |
 | ☒ handwired/void16: NO_ACTION_MACRO in config.h is no longer a valid option and should be removed
 | ☒ handwired/void16: NO_ACTION_FUNCTION in config.h is no longer a valid option and should be removed
 |
Generating: .build/obj_handwired_void16/src/default_keyboard.c                                      [WARNINGS]
 |
 | ☒ handwired/void16: NO_ACTION_MACRO in config.h is no longer a valid option and should be removed
 | ☒ handwired/void16: NO_ACTION_FUNCTION in config.h is no longer a valid option and should be removed
 |
Generating: .build/obj_handwired_void16/src/default_keyboard.h                                      [WARNINGS]
 |
 | ☒ handwired/void16: NO_ACTION_MACRO in config.h is no longer a valid option and should be removed
 | ☒ handwired/void16: NO_ACTION_FUNCTION in config.h is no longer a valid option and should be removed
 |
Generating: .build/obj_handwired_void16/src/layouts.h                                               [WARNINGS]
 |
 | ☒ handwired/void16: NO_ACTION_MACRO in config.h is no longer a valid option and should be removed
 | ☒ handwired/void16: NO_ACTION_FUNCTION in config.h is no longer a valid option and should be removed
 |
Compiling: keyboards/handwired/void16/void16.c                                                      [OK]
Compiling: .build/obj_handwired_void16/src/default_keyboard.c                                       [OK]
Compiling: quantum/keymap_introspection.c                                                           [OK]
Compiling: quantum/quantum.c                                                                        [OK]
Compiling: quantum/bitwise.c                                                                        [OK]
Compiling: quantum/led.c                                                                            [OK]
Compiling: quantum/action.c                                                                         [OK]
Compiling: quantum/action_layer.c                                                                   [OK]
Compiling: quantum/action_tapping.c                                                                 [OK]
Compiling: quantum/action_util.c                                                                    [OK]
Compiling: quantum/eeconfig.c                                                                       [OK]
Compiling: quantum/keyboard.c                                                                       [OK]
Compiling: quantum/keymap_common.c                                                                  [OK]
Compiling: quantum/keycode_config.c                                                                 [OK]
Compiling: quantum/sync_timer.c                                                                     [OK]
Compiling: quantum/logging/debug.c                                                                  [OK]
Compiling: quantum/logging/sendchar.c                                                               [OK]
Compiling: quantum/bootmagic/bootmagic_lite.c                                                       [OK]
Compiling: quantum/bootmagic/magic.c                                                                [OK]
Compiling: quantum/matrix_common.c                                                                  [OK]
Compiling: quantum/matrix.c                                                                         [OK]
Compiling: quantum/debounce/sym_defer_g.c                                                           [OK]
Compiling: quantum/main.c                                                                           [OK]
Compiling: quantum/mousekey.c                                                                       [OK]
Compiling: quantum/via.c                                                                            [OK]
Compiling: quantum/process_keycode/process_magic.c                                                  [OK]
Compiling: quantum/send_string/send_string.c                                                        [OK]
Compiling: quantum/encoder.c                                                                        [OK]
Compiling: quantum/dynamic_keymap.c                                                                 [OK]
Compiling: quantum/process_keycode/process_grave_esc.c                                              [OK]
Compiling: quantum/process_keycode/process_space_cadet.c                                            [OK]
Assembling: platforms/avr/xprintf.S                                                                 [OK]
Compiling: platforms/avr/printf.c                                                                   [OK]
Compiling: tmk_core/protocol/host.c                                                                 [OK]
Compiling: tmk_core/protocol/report.c                                                               [OK]
Compiling: tmk_core/protocol/usb_device_state.c                                                     [OK]
Compiling: tmk_core/protocol/usb_util.c                                                             [OK]
Compiling: platforms/suspend.c                                                                      [OK]
Compiling: platforms/avr/hardware_id.c                                                              [OK]
Compiling: platforms/avr/platform.c                                                                 [OK]
Compiling: platforms/avr/suspend.c                                                                  [OK]
Compiling: platforms/avr/timer.c                                                                    [OK]
Compiling: platforms/avr/bootloaders/caterina.c                                                     [OK]
Compiling: tmk_core/protocol/lufa/lufa.c                                                            [OK]
Compiling: tmk_core/protocol/usb_descriptor.c                                                       [OK]
Compiling: lib/lufa/LUFA/Drivers/USB/Class/Common/HIDParser.c                                       [OK]
Compiling: lib/lufa/LUFA/Drivers/USB/Core/AVR8/Device_AVR8.c                                        [OK]
Compiling: lib/lufa/LUFA/Drivers/USB/Core/AVR8/EndpointStream_AVR8.c                                [OK]
Compiling: lib/lufa/LUFA/Drivers/USB/Core/AVR8/Endpoint_AVR8.c                                      [OK]
Compiling: lib/lufa/LUFA/Drivers/USB/Core/AVR8/Host_AVR8.c                                          [OK]
Compiling: lib/lufa/LUFA/Drivers/USB/Core/AVR8/PipeStream_AVR8.c                                    [OK]
Compiling: lib/lufa/LUFA/Drivers/USB/Core/AVR8/Pipe_AVR8.c                                          [OK]
Compiling: lib/lufa/LUFA/Drivers/USB/Core/AVR8/USBController_AVR8.c                                 [OK]
Compiling: lib/lufa/LUFA/Drivers/USB/Core/AVR8/USBInterrupt_AVR8.c                                  [OK]
Compiling: lib/lufa/LUFA/Drivers/USB/Core/ConfigDescriptors.c                                       [OK]
Compiling: lib/lufa/LUFA/Drivers/USB/Core/DeviceStandardReq.c                                       [OK]
Compiling: lib/lufa/LUFA/Drivers/USB/Core/Events.c                                                  [OK]
Compiling: lib/lufa/LUFA/Drivers/USB/Core/HostStandardReq.c                                         [OK]
Compiling: lib/lufa/LUFA/Drivers/USB/Core/USBTask.c                                                 [OK]
Compiling: tmk_core/protocol/lufa/usb_util.c                                                        [OK]
Linking: .build/handwired_void16_default.elf                                                        [OK]
Creating load file for flashing: .build/handwired_void16_default.hex                                [OK]
Copying handwired_void16_default.hex to qmk_firmware folder                                         [OK]
Checking file size of handwired_void16_default.hex                                                  [OK]
 * The firmware size is fine - 18958/28672 (66%, 9714 bytes free)`

**Comment by darknessblade** [comment]
Removing every reference to the encoder from the settings seems to fix it, though I do not have the VIA Json file. And VIA does not automatically detect the keyboard/macropad

**Comment by victorlucachi** [comment]
> Removing every reference to the encoder from the settings seems to fix it, though I do not have the VIA Json file. And VIA does not automatically detect the keyboard/macropad

[VOID16 Via Definitions](https://github.com/victorlucachi/void16/blob/master/void16_via_definitions.json)

**Comment by darknessblade** [comment]
With the Via definitions it seems to be working fine, I am able to remap it as well, without any issue.

If I encounter any new issues I will report back

**Comment by darknessblade** [comment]
The only Issue I get is when I try to sideload the JSON file in VIAL

____________
Unsupported protocol version!
Please download latest Vial from https://get.vial.today/
____________
 File "main_window.py", line 284, in on_device_selected
  File "main_window.py", line 304, in rebuild
  File "editor\keymap_editor.py", line 125, in rebuild
  File "keycodes.py", line 870, in recreate_keyboard_keycodes

AttributeError: 'Keyboard' object has no attribute 'tap_dance_count'
____________
