### ISSUE TITLE
EC11 encoder pinout diagram 

### ISSUE THREAD

**Issue by r4ph74** [victorlucachi/void9#8]
HI Victor  It's me again . 

I want to make a new one with encoder since I have successfully run the vial.  But I still confuse with the pinout. 

the encoder have 5 pin  2 + 3 . I know the 2 pin one is for colom and other for the row, both pin act as  a button .  The other 3 pin is for rotary up and down.  the 2 pin is already known as you wrote, but how about the last pin ? where does it go ?  does it go to the same colom as the other 2 pin ? or goes to "gnd" pin ? 

if you have the diagram that would be delightful. 

Thanks in Advance 

Rafael

**Comment by victorlucachi** [comment]
hey Rafael,

I dont have any diagrams, but you got it right.

the side with two pins gets wired into the key matrix. on the other side, out of the three pins the upper and lower ones are connected according to the pinout in the readme (pin A to B2 and pin B to B3), while the third middle pin gets connected to ground on the mcu.

**Comment by r4ph74** [comment]
Ahh.. Thanks Victor!..

**Comment by r4ph74** [comment]
hi Victor  it's me again . 

 I have soldered Pin B1 (15)  gnd (ground) and B2 (16) .. but seems the vial doesn't recognise it ... 

the press button works good as usual .  

did I miss something ?

**Comment by victorlucachi** [comment]
> I have soldered Pin B1 (15) gnd (ground) and B2 (16) .. but seems the vial doesn't recognise it ...

hey Rafael,

the pairings for the encoders are the following:
- B1 and F7
- B2 and B3

you will have to resolder one of the wires from you current scheme: 
- either remove B1 (15), and resolder it to B3 (14)
- or remove B2 (16), and resolder it to F7(18/A0)

edit: sidenote, in vial you have to select the layout tab and choose the encoder position, for it to show up in the keymap tab

![image](https://user-images.githubusercontent.com/2669084/219746864-b8253056-1004-48d2-93c2-85d43264390a.png)

**Comment by r4ph74** [comment]
Thanks VIctor , it's working  now. I missed how to read the pinout  you mentioned  in readme.

**Comment by victorlucachi** [comment]
> Thanks VIctor , it's working now. I missed how to read the pinout you mentioned in readme.

no worries, glad it's working!

the pinout table is a bit confusing, I'll try to make things a little clearer in the future, and add mcu/encoder diagrams and highlight the used pins.

**Comment by r4ph74** [comment]
That would be great. Thanks Victor.
