### ISSUE TITLE
Waveshare rp2040 controller doesn't fit

### ISSUE THREAD

**Issue by Sparticuz** [victorlucachi/void9#9]
The chips on the bottom of the waveshare rp2040 won't allow it to slide into the controller slides. Seems like a 1 or 2 mm spacer needs to be cut out of the middle

![image](https://github.com/victorlucachi/void9/assets/161913/9e121a63-0fd1-4f74-b530-ace6fa3db76a)
![image](https://github.com/victorlucachi/void9/assets/161913/18d1f830-df71-47a6-a3e6-e47f4b444185)
![image](https://github.com/victorlucachi/void9/assets/161913/207bbebc-4de9-47da-956b-a7283ac9496b)

**Comment by victorlucachi** [comment]
this thing will have close to no structural integrity at all 😅. please let me know if it works.

[waveshare-rp2040.zip](https://github.com/victorlucachi/void9/files/11849325/waveshare-rp2040.zip)

**Comment by Sparticuz** [comment]
Lol, will do. It looks like about half that could probably be put back. Though, also once it's screwed in, that will add back a ton of rigidity. I really wish i had my calipurs here at work. :/

**Comment by Sparticuz** [comment]
It worked much better, the only improvement would be to make the screw holes smaller because the m2 insert i was using was quite a bit smaller than the opening. I had to wiggle the insert around inside the hole to get it to melt the sides.

**Comment by victorlucachi** [comment]
sweet. the inserts that I'm using (also linked in the bom) have an outer diameter of 3.5mm; they should fit the part.

**Comment by Sparticuz** [comment]
I used the same inserts on the top part and they fit perfect, but on the controller mount the hole was much larger. Everything is working well though! thank you for altering the stl!

**Comment by bukowa** [comment]
Hey, how does the current project work with RP2040 Zero ?
